version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: 'laravel_app_locadora_api'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT}:3306
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  localstack:
    container_name: 'localstack'
    image: localstack/localstack
    network_mode: bridge
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,ssm,s3,apigateway,lambda
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    ports:
      - 4566:4566
      - 4572:4572

    volumes:
      - '${TEMPDIR:-/tmp/localstack}:/temp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  db: null
